title: Template de Site Pessoal
description: Coisas possíveis a ser feitas em um site
markdown: kramdown

# Customização
permalink: pretty

# Estrutura de diretórios
source: .
includes_dir: src/_includes
layouts_dir: src/_layouts
data_dir: src/_data
plugins_dir: src/_plugins

# Sass/SCSS
sass:
  sass_dir: src/_sass
  style: compressed

# Configurações do Kramdown (processador Markdown)
kramdown:
  input: GFM  # GitHub Flavored Markdown
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# GitHub Pages
url: "https://gatilhoroxo.github.io"
baseurl: "" # Use "/site-attempt" em produção

# Incluir diretórios customizados
include:
  - content

# Manter arquivos estáticos
keep_files:
  - assets

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"


